version: '3.8'

services:
  # Prowlarr - Indexer Manager (Deploy first as others depend on it)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Sonarr - TV Series Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - sonarr_config:/config
      - /Users/morlock/fun/newmedia/media-data/tv:/tv
      - /Users/morlock/fun/newmedia/media-data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media-network
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Radarr - Movie Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - radarr_config:/config
      - /Users/morlock/fun/newmedia/media-data/movies:/movies
      - /Users/morlock/fun/newmedia/media-data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media-network
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Lidarr - Music Management
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - lidarr_config:/config
      - /Users/morlock/fun/newmedia/media-data/music:/music
      - /Users/morlock/fun/newmedia/media-data/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - media-network
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  prowlarr_config:
    driver: local
  sonarr_config:
    driver: local
  radarr_config:
    driver: local
  lidarr_config:
    driver: local

networks:
  media-network:
    driver: bridge
    name: media-network