# Ultimate Media Server 2025 - ARM64 Compatible
# =====================================================================
# Compatible with Apple Silicon (M1/M2/M3) and ARM64 systems
# Usage: docker compose --profile core --profile media up -d

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  downloads:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  jellyfin_config:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  bazarr_config:
  lidarr_config:
  qbittorrent_config:
  sabnzbd_config:
  overseerr_config:
  prometheus_data:
  grafana_data:
  loki_data:
  tautulli_config:
  homepage_config:
  portainer_data:

x-security-opts: &security-opts
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

x-common-env: &common-env
  TZ: ${TZ:-America/New_York}
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

services:
  # =================================================================
  # PROFILE: core - Essential Infrastructure Services
  # =================================================================
  
  redis:
    profiles: ["core"]
    image: redis:7-alpine
    container_name: redis
    <<: *security-opts
    networks:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis_data:/data

  postgres:
    profiles: ["core"]
    image: postgres:16-alpine
    container_name: postgres
    <<: *security-opts
    networks:
      - backend
    environment:
      POSTGRES_USER: ${DB_USER:-mediaserver}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-mediadb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # =================================================================
  # PROFILE: media - Media Streaming Services
  # =================================================================
  
  jellyfin:
    profiles: ["media"]
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    <<: *security-opts
    networks:
      - frontend
    environment:
      <<: *common-env
      JELLYFIN_PublishedServerUrl: http://localhost:8096
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_PATH:-./media-data}:/media:ro
      - /tmp:/transcodes
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"

  # =================================================================
  # PROFILE: automation - Media Automation Services (ARM64 Compatible)
  # =================================================================
  
  sonarr:
    profiles: ["automation"]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    <<: *security-opts
    networks:
      - frontend
      - backend
      - downloads
    environment:
      <<: *common-env
    volumes:
      - sonarr_config:/config
      - ${MEDIA_PATH:-./media-data}:/media
      - ${DOWNLOADS_PATH:-./media-data/downloads}:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"

  radarr:
    profiles: ["automation"]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    <<: *security-opts
    networks:
      - frontend
      - backend
      - downloads
    environment:
      <<: *common-env
    volumes:
      - radarr_config:/config
      - ${MEDIA_PATH:-./media-data}:/media
      - ${DOWNLOADS_PATH:-./media-data/downloads}:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"

  prowlarr:
    profiles: ["automation"]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    <<: *security-opts
    networks:
      - frontend
      - backend
    environment:
      <<: *common-env
    volumes:
      - prowlarr_config:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"

  bazarr:
    profiles: ["automation"]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    <<: *security-opts
    networks:
      - frontend
      - backend
    environment:
      <<: *common-env
    volumes:
      - bazarr_config:/config
      - ${MEDIA_PATH:-./media-data}:/media
    ports:
      - "${BAZARR_PORT:-6767}:6767"

  lidarr:
    profiles: ["automation"]
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    <<: *security-opts
    networks:
      - frontend
      - backend
      - downloads
    environment:
      <<: *common-env
    volumes:
      - lidarr_config:/config
      - ${MEDIA_PATH:-./media-data}:/media
      - ${DOWNLOADS_PATH:-./media-data/downloads}:/downloads
    ports:
      - "${LIDARR_PORT:-8686}:8686"

  # =================================================================
  # PROFILE: downloads - Download Clients
  # =================================================================
  
  qbittorrent:
    profiles: ["downloads"]
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    <<: *security-opts
    networks:
      - frontend
      - downloads
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
    volumes:
      - qbittorrent_config:/config
      - ${DOWNLOADS_PATH:-./media-data/downloads}:/downloads
    ports:
      - "${QBITTORRENT_PORT:-8080}:8080"
      - "6881:6881"
      - "6881:6881/udp"

  sabnzbd:
    profiles: ["downloads"]
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    <<: *security-opts
    networks:
      - frontend
      - downloads
    environment:
      <<: *common-env
    volumes:
      - sabnzbd_config:/config
      - ${DOWNLOADS_PATH:-./media-data/downloads}:/downloads
    ports:
      - "${SABNZBD_PORT:-8081}:8080"

  # =================================================================
  # PROFILE: requests - Media Request Management
  # =================================================================
  
  overseerr:
    profiles: ["requests"]
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    <<: *security-opts
    networks:
      - frontend
      - backend
    environment:
      <<: *common-env
    volumes:
      - overseerr_config:/app/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"

  # =================================================================
  # PROFILE: monitoring - System Monitoring
  # =================================================================
  
  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:latest
    container_name: prometheus
    <<: *security-opts
    networks:
      - monitoring
      - backend
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:latest
    container_name: grafana
    <<: *security-opts
    networks:
      - frontend
      - monitoring
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-changeme}
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

  loki:
    profiles: ["monitoring"]
    image: grafana/loki:latest
    container_name: loki
    <<: *security-opts
    networks:
      - monitoring
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  tautulli:
    profiles: ["monitoring"]
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    <<: *security-opts
    networks:
      - frontend
      - backend
    environment:
      <<: *common-env
    volumes:
      - tautulli_config:/config
    ports:
      - "${TAUTULLI_PORT:-8181}:8181"

  # =================================================================
  # PROFILE: management - Container & System Management
  # =================================================================
  
  homepage:
    profiles: ["management"]
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    <<: *security-opts
    networks:
      - frontend
    environment:
      <<: *common-env
    volumes:
      - homepage_config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3001}:3000"

  portainer:
    profiles: ["management"]
    image: portainer/portainer-ce:latest
    container_name: portainer
    <<: *security-opts
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
      - "${PORTAINER_HTTPS_PORT:-9443}:9443"