# Fixed Media Server Configuration
# This file shows the corrected volume mappings for direct access to /Volumes/Plex media

version: '3.9'

x-common-variables: &common-variables
  TZ: ${TZ:-America/New_York}
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *common-variables
    volumes:
      - jellyfin-config:/config
      # FIXED: Direct mapping to actual media location
      - /Volumes/Plex/data/Media:/media
      - /dev/dri:/dev/dri # Hardware acceleration
    ports:
      - "8096:8096"
      - "8920:8920" # HTTPS
      - "7359:7359/udp" # Discovery
      - "1900:1900/udp" # DLNA
    networks:
      - media-net
    restart: unless-stopped
    labels:
      - "homepage.group=Media"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.png"
      - "homepage.href=http://jellyfin:8096"
      - "homepage.description=Free Media Server"

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      <<: *common-variables
      PLEX_CLAIM: ${PLEX_CLAIM:-}
      ADVERTISE_IP: ${ADVERTISE_IP:-}
    volumes:
      - plex-config:/config
      # FIXED: Direct mapping to actual media location
      - /Volumes/Plex/data/Media:/media
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    networks:
      - media-net
    restart: unless-stopped
    labels:
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=plex.png"
      - "homepage.href=http://plex:32400/web"
      - "homepage.description=Premium Media Server"

volumes:
  jellyfin-config:
    driver: local
  plex-config:
    driver: local

networks:
  media-net:
    driver: bridge