#!/bin/bash

echo "🐳 Portainer Setup Helper"
echo "========================"
echo ""
echo "Portainer is running but needs initial configuration."
echo ""
echo "📝 Setup Instructions:"
echo "1. Open Portainer: http://localhost:9000"
echo "2. You'll see the initial setup screen"
echo "3. Create an admin user:"
echo "   - Username: admin (or your choice)"
echo "   - Password: Choose a strong password (min 12 characters)"
echo ""
echo "4. Click 'Create user'"
echo ""
echo "5. On the next screen, select:"
echo "   - 'Docker - Manage the local Docker environment'"
echo "   - Click 'Connect'"
echo ""
echo "6. You're now in Portainer! You can:"
echo "   - View all containers"
echo "   - Start/stop services"
echo "   - Check logs"
echo "   - Manage volumes"
echo "   - Deploy new stacks"
echo ""
echo "🔧 Quick Actions:"
echo "   - View logs: docker logs portainer"
echo "   - Restart: docker restart portainer"
echo "   - Reset (WARNING: removes data): docker stop portainer && docker rm portainer && docker volume rm portainer_data"
echo ""
echo "Opening Portainer in your browser..."
open http://localhost:9000