# Alertmanager Configuration for Media Server
# Comprehensive alerting with smart routing and escalation

global:
  smtp_smarthost: '${SMTP_HOST:-localhost:587}'
  smtp_from: '${ALERT_FROM_EMAIL:-alerts@mediaserver.local}'
  smtp_auth_username: '${SMTP_USERNAME:-}'
  smtp_auth_password: '${SMTP_PASSWORD:-}'
  smtp_require_tls: true

# Notification templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # Critical infrastructure alerts
    - match_re:
        alertname: '(InstanceDown|ServiceDown|HighCPUUsage|HighMemoryUsage|DiskSpaceRunningOut)'
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 15m
    
    # Media server specific alerts
    - match_re:
        service: '(jellyfin|plex|emby|sonarr|radarr|qbittorrent)'
      receiver: 'media-alerts'
      group_wait: 30s
      repeat_interval: 30m
    
    # Download and automation alerts
    - match_re:
        service: '(qbittorrent|sabnzbd|sonarr|radarr|lidarr|bazarr|prowlarr)'
      receiver: 'download-alerts'
      group_wait: 1m
      repeat_interval: 1h
    
    # Performance alerts
    - match_re:
        alertname: '(HighTranscodingLoad|SlowDownloadSpeed|HighNetworkLatency)'
      receiver: 'performance-alerts'
      group_wait: 2m
      repeat_interval: 30m
    
    # Security alerts
    - match_re:
        alertname: '(UnauthorizedAccess|SuspiciousActivity|CertificateExpiring)'
      receiver: 'security-alerts'
      group_wait: 5s
      repeat_interval: 10m
    
    # Storage alerts
    - match_re:
        alertname: '(DiskSpaceRunningOut|MediaLibraryFull|BackupFailed)'
      receiver: 'storage-alerts'
      group_wait: 1m
      repeat_interval: 2h
    
    # Warning alerts (non-critical)
    - match:
        severity: 'warning'
      receiver: 'warning-alerts'
      group_wait: 5m
      repeat_interval: 2h

# Inhibit rules to reduce noise
inhibit_rules:
  # If instance is down, don't alert on individual services
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: '(ServiceDown|HighCPUUsage|HighMemoryUsage)'
    equal: ['instance']
  
  # If service is down, don't alert on performance metrics
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(SlowResponse|HighLatency)'
    equal: ['service']

# Notification receivers
receivers:
  # Default receiver for uncategorized alerts
  - name: 'default-receiver'
    email_configs:
      - to: '${ADMIN_EMAIL:-admin@mediaserver.local}'
        subject: '🚨 Media Server Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
        html: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Media Server Alert</title>
            <style>
              body { font-family: Arial, sans-serif; }
              .alert { background: #f8f9fa; border-left: 4px solid #dc3545; padding: 15px; margin: 10px 0; }
              .critical { border-left-color: #dc3545; }
              .warning { border-left-color: #ffc107; }
              .info { border-left-color: #17a2b8; }
            </style>
          </head>
          <body>
            <h2>🚨 Media Server Alert</h2>
            {{ range .Alerts }}
            <div class="alert {{ .Labels.severity }}">
              <h3>{{ .Annotations.summary }}</h3>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <p><strong>Service:</strong> {{ .Labels.service }}</p>
              <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
              <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
              <p><strong>Started:</strong> {{ .StartsAt }}</p>
            </div>
            {{ end }}
          </body>
          </html>

  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    email_configs:
      - to: '${ADMIN_EMAIL:-admin@mediaserver.local}'
        subject: '🔥 CRITICAL: Media Server Issue - {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT! Immediate attention required.
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    webhook_configs:
      - url: '${DISCORD_WEBHOOK_URL:-}'
        send_resolved: true
        title: '🔥 Critical Media Server Alert'
        message: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          Service: `{{ .Labels.service }}`
          {{ end }}

  # Media server alerts
  - name: 'media-alerts'
    email_configs:
      - to: '${MEDIA_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '📺 Media Server: {{ .GroupLabels.alertname }}'
        body: |
          Media Server Alert:
          
          {{ range .Alerts }}
          Service: {{ .Labels.service }}
          Issue: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Check the dashboard: http://grafana:3000

  # Download system alerts
  - name: 'download-alerts'
    email_configs:
      - to: '${DOWNLOAD_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '⬇️ Download System: {{ .GroupLabels.alertname }}'
        body: |
          Download System Alert:
          
          {{ range .Alerts }}
          Service: {{ .Labels.service }}
          Issue: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  # Performance alerts
  - name: 'performance-alerts'
    email_configs:
      - to: '${PERFORMANCE_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '⚡ Performance Issue: {{ .GroupLabels.alertname }}'
        body: |
          Performance Alert:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Current Value: {{ .Annotations.value }}
          Threshold: {{ .Annotations.threshold }}
          {{ end }}
          
          Performance Dashboard: http://grafana:3000/d/performance

  # Security alerts
  - name: 'security-alerts'
    email_configs:
      - to: '${SECURITY_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY ALERT - Immediate Review Required
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Source: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
          
          Please review security logs immediately.
    webhook_configs:
      - url: '${SECURITY_WEBHOOK_URL:-}'
        send_resolved: true

  # Storage alerts
  - name: 'storage-alerts'
    email_configs:
      - to: '${STORAGE_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '💾 Storage Alert: {{ .GroupLabels.alertname }}'
        body: |
          Storage System Alert:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Location: {{ .Labels.mountpoint }}
          {{ end }}

  # Warning alerts (low priority)
  - name: 'warning-alerts'
    email_configs:
      - to: '${WARNING_ALERTS_EMAIL:-${ADMIN_EMAIL:-admin@mediaserver.local}}'
        subject: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        body: |
          Warning Alert:
          
          {{ range .Alerts }}
          Service: {{ .Labels.service }}
          Warning: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          This is a warning and may not require immediate action.

# Silence configuration
time_intervals:
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        location: 'UTC'

  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']
        location: 'UTC'