#\!/bin/bash
# Production Deployment Script
echo "🚀 Deploying Ultimate Media Server (Production)"
echo "=============================================="
echo ""
echo "This deployment includes:"
echo "  • 30+ integrated services"
echo "  • AI-enhanced features"
echo "  • Modern dashboard"
echo "  • Single container architecture"
echo ""
echo "To deploy:"
echo "  1. Run: docker-compose -f docker-compose.production.yml build"
echo "  2. Run: docker-compose -f docker-compose.production.yml up -d"
echo "  3. Access: http://localhost"
echo ""
echo "Services will be available at:"
echo "  • Dashboard: http://localhost:3000"
echo "  • Jellyfin:  http://localhost:8096"
echo "  • Sonarr:    http://localhost:8989"
echo "  • Radarr:    http://localhost:7878"
