---
# Authelia Configuration - 2025 Production Ready
# https://www.authelia.com/configuration/prologue/introduction/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  asset_path: /config/assets/
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
  headers:
    csp_template: ""
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s

log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true

theme: dark

default_redirection_url: https://{{DOMAIN}}
default_2fa_method: totp

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      key_length: 32
      salt_length: 16

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  rules:
    # Public access
    - domain: "{{DOMAIN}}"
      policy: bypass
    - domain: "requests.{{DOMAIN}}"
      policy: bypass
    - domain: "jellyfin.{{DOMAIN}}"
      policy: bypass
      resources:
        - "^/web/.*$"
        - "^/swagger/.*$"
        - "^/api/.*$"
    
    # Single factor auth for less sensitive services
    - domain:
        - "overseerr.{{DOMAIN}}"
        - "ombi.{{DOMAIN}}"
        - "tautulli.{{DOMAIN}}"
        - "speedtest.{{DOMAIN}}"
      policy: one_factor
    
    # Two factor auth for sensitive services
    - domain:
        - "traefik.{{DOMAIN}}"
        - "auth.{{DOMAIN}}"
        - "portainer.{{DOMAIN}}"
        - "grafana.{{DOMAIN}}"
        - "prometheus.{{DOMAIN}}"
        - "backup.{{DOMAIN}}"
        - "files.{{DOMAIN}}"
      policy: two_factor
    
    # Admin group access
    - domain:
        - "*.{{DOMAIN}}"
      subject:
        - "group:admins"
      policy: two_factor
    
    # Media group access
    - domain:
        - "sonarr.{{DOMAIN}}"
        - "radarr.{{DOMAIN}}"
        - "lidarr.{{DOMAIN}}"
        - "readarr.{{DOMAIN}}"
        - "bazarr.{{DOMAIN}}"
        - "prowlarr.{{DOMAIN}}"
        - "qbittorrent.{{DOMAIN}}"
        - "sabnzbd.{{DOMAIN}}"
        - "tdarr.{{DOMAIN}}"
        - "filebot.{{DOMAIN}}"
        - "autobrr.{{DOMAIN}}"
      subject:
        - "group:media"
        - "group:admins"
      policy: two_factor
    
    # User group access
    - domain:
        - "jellyfin.{{DOMAIN}}"
        - "emby.{{DOMAIN}}"
        - "plex.{{DOMAIN}}"
        - "music.{{DOMAIN}}"
        - "comics.{{DOMAIN}}"
        - "books.{{DOMAIN}}"
        - "audiobooks.{{DOMAIN}}"
        - "photos.{{DOMAIN}}"
        - "immich.{{DOMAIN}}"
        - "kavita.{{DOMAIN}}"
        - "rss.{{DOMAIN}}"
      subject:
        - "group:users"
        - "group:media"
        - "group:admins"
      policy: one_factor
    
    # Internal network bypass
    - domain: "*.{{DOMAIN}}"
      networks:
        - internal
      policy: one_factor

session:
  name: authelia_session
  domain: {{DOMAIN}}
  same_site: lax
  secret: {{SESSION_SECRET}}
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: redis_authelia
    port: 6379
    password: {{REDIS_PASSWORD}}
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
    tls:
      skip_verify: false
      minimum_version: TLS1.2

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: {{ENCRYPTION_KEY}}
  postgres:
    host: postgres_authelia
    port: 5432
    database: authelia
    schema: public
    username: authelia
    password: {{POSTGRES_PASSWORD}}
    timeout: 5s
    ssl:
      mode: disable
      skip_verify: false
      minimum_version: TLS1.2

notifier:
  disable_startup_check: false
  smtp:
    host: {{SMTP_HOST}}
    port: {{SMTP_PORT}}
    timeout: 5s
    username: {{SMTP_USERNAME}}
    password: {{SMTP_PASSWORD}}
    sender: "Authelia <{{SMTP_FROM}}>"
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2

identity_providers:
  oidc:
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: public_clients_only
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    jwks:
      - key: |
          {{OIDC_PRIVATE_KEY}}
        algorithm: RS256
    clients:
      - id: jellyfin
        description: Jellyfin Media Server
        secret: {{JELLYFIN_OIDC_SECRET}}
        public: false
        authorization_policy: two_factor
        consent_mode: implicit
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://jellyfin.{{DOMAIN}}/sso/OID/redirect/authelia
        userinfo_signing_algorithm: none
      - id: grafana
        description: Grafana
        secret: {{GRAFANA_OIDC_SECRET}}
        public: false
        authorization_policy: two_factor
        consent_mode: implicit
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://grafana.{{DOMAIN}}/login/generic_oauth
        userinfo_signing_algorithm: none

telemetry:
  metrics:
    enabled: true
    address: tcp://0.0.0.0:9959
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: 6s
      write: 6s
      idle: 30s

...