---
# Simple Authelia configuration for testing
server:
  address: 'tcp://0.0.0.0:9091'
  disable_healthcheck: false
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: 'info'

jwt_secret: '2daa9982739178ccea66c5aeac02ae364ffc28f2bc76cb79e0d44037a8c76c6f1ea7da954466148b5ed79cf2d959d1869fd82a63443632f2d219a0cfc4e6e817'

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'auth.morloksmaze.com'
      policy: 'bypass'
    - domain: '*.morloksmaze.com'
      policy: 'one_factor'

session:
  secret: 'd8620c149267b24ac3f951ea9193a8236dc56818857264ec8dd6a8115518b443f8ed55825c7de6c1c53cfb8a85e477deb003f0e4fa76440cbddb9a8ca6d8f9c1'
  cookies:
    - domain: 'morloksmaze.com'
      authelia_url: 'https://auth.morloksmaze.com'
      default_redirection_url: 'https://home.morloksmaze.com'
  redis:
    host: 'redis'
    port: 6379
    password: '2ea1153e4adeb30c498fa053884c156ba96e73ffd92b5658bcb87d193ed6155f'

regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

storage:
  encryption_key: '7a5iekFUq4/6e23HQMFT7EM2FNoLNNLaLbRE9jm8KXM='
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: '/config/notification.txt'