version: '3.8'

services:
  quantum-security:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantum-security-server
    restart: unless-stopped
    ports:
      - "3000:3000"     # HTTP (redirects to HTTPS)
      - "8443:8443"     # Quantum-resistant HTTPS
    environment:
      - NODE_ENV=production
      - PORT=3000
      - QUANTUM_TLS_PORT=8443
      - HOST=0.0.0.0
      - HYBRID_MODE=x25519-mlkem768
      - SIGNATURE_ALGORITHM=ml-dsa-65
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:8443
    volumes:
      - quantum-certs:/app/certs
      - quantum-logs:/app/logs
    networks:
      - quantum-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: quantum-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass quantumsecurepass123
    volumes:
      - redis-data:/data
    networks:
      - quantum-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: quantum-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - quantum-network

  grafana:
    image: grafana/grafana:latest
    container_name: quantum-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=quantumsecure
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - "3001:3000"
    networks:
      - quantum-network
    depends_on:
      - prometheus

  nginx:
    image: nginx:alpine
    container_name: quantum-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    networks:
      - quantum-network
    depends_on:
      - quantum-security

volumes:
  quantum-certs:
  quantum-logs:
  redis-data:
  prometheus-data:
  grafana-data:
  nginx-cache:

networks:
  quantum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16