global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'media-server-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - Host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'media-server-host'

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9417']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      # Drop unnecessary metrics
      - source_labels: [__name__]
        regex: 'container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)'
        action: drop

  # Process Exporter
  - job_name: 'process'
    static_configs:
      - targets: ['process-exporter:9256']

  # Pushgateway
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  # BlackBox Exporter - Endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://jellyfin:8096
          - http://sonarr:8989
          - http://radarr:7878
          - http://prowlarr:9696
          - http://lidarr:8686
          - http://bazarr:6767
          - http://overseerr:5055
          - http://tautulli:8181
          - http://homepage:3000
          - http://qbittorrent:8080
          - http://sabnzbd:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Media Server specific metrics
  - job_name: 'jellyfin'
    static_configs:
      - targets: ['jellyfin:8096']
    metrics_path: '/metrics'

  # Arr Suite metrics (if exposed)
  - job_name: 'sonarr'
    static_configs:
      - targets: ['sonarr:8989']
    metrics_path: '/api/v3/system/status'
    params:
      apikey: ['${SONARR_API_KEY}']

  - job_name: 'radarr'
    static_configs:
      - targets: ['radarr:7878']
    metrics_path: '/api/v3/system/status'
    params:
      apikey: ['${RADARR_API_KEY}']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Service discovery for Docker containers
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Only keep containers that have prometheus labels
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        regex: true
        action: keep
      # Use the prometheus.io/port label to set the scrape port
      - source_labels: [__meta_docker_container_label_prometheus_io_port]
        target_label: __address__
        replacement: $1
      # Set the job name from container name
      - source_labels: [__meta_docker_container_name]
        target_label: job
        regex: '/(.*)' 
        replacement: '$1'
      # Add container labels
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service

  # Custom Media Server Exporter
  - job_name: 'media-server-exporter'
    static_configs:
      - targets: ['media-server-exporter:9500']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # Performance Monitor
  - job_name: 'performance-monitor'
    static_configs:
      - targets: ['performance-monitor:9501']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Tautulli Exporter
  - job_name: 'tautulli-exporter'
    static_configs:
      - targets: ['tautulli-exporter:9487']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # Speed Test Exporter
  - job_name: 'speedtest'
    static_configs:
      - targets: ['speedtest-exporter:9798']
    scrape_interval: 1800s  # Every 30 minutes
    scrape_timeout: 60s
    metrics_path: '/metrics'

  # Hardware Monitoring
  - job_name: 'smartctl'
    static_configs:
      - targets: ['smartctl-exporter:9633']
    scrape_interval: 300s  # Every 5 minutes
    metrics_path: '/metrics'

  # Vector Log Metrics
  - job_name: 'vector-logs'
    static_configs:
      - targets: ['vector:9598']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Vector Health
  - job_name: 'vector-health'
    static_configs:
      - targets: ['vector:9599']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # SNMP Monitoring (if configured)
  - job_name: 'snmp'
    static_configs:
      - targets: ['snmp-exporter:9116']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # Additional BlackBox checks for external services
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [ssl_cert]
    static_configs:
      - targets:
          - https://google.com
          - https://github.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Network latency monitoring
  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
          - google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115