# Promtail Configuration - Production Media Stack
# ===============================================
# Log collection and forwarding to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  # Docker container logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging']
        target_label: 'logging'
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            message: msg
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:

  # Media stack application logs
  - job_name: media-stack
    static_configs:
      - targets:
          - localhost
        labels:
          job: media_stack
          __path__: /logs/**/*.log
    pipeline_stages:
      - match:
          selector: '{job="media_stack"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s+(?P<level>\w+)\s+(?P<message>.*)'
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'
            - labels:
                level:

  # Jellyfin logs
  - job_name: jellyfin
    static_configs:
      - targets:
          - localhost
        labels:
          job: jellyfin
          __path__: /logs/jellyfin/*.log
    pipeline_stages:
      - match:
          selector: '{job="jellyfin"}'
          stages:
            - regex:
                expression: '\[(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\]\s+\[(?P<level>\w+)\]\s+\[(?P<component>[\w\.]+)\]\s+(?P<message>.*)'
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05.000'
            - labels:
                level:
                component:

  # Traefik access logs
  - job_name: traefik_access
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik_access
          __path__: /logs/access.log
    pipeline_stages:
      - json:
          expressions:
            method: RequestMethod
            status: DownstreamStatus
            duration: Duration
            size: DownstreamContentSize
            remote_addr: ClientAddr
            request_uri: RequestPath
      - labels:
          method:
          status:

  # Authelia logs
  - job_name: authelia
    static_configs:
      - targets:
          - localhost
        labels:
          job: authelia
          __path__: /logs/authelia.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            message: msg
            username: username
            remote_ip: remote_ip
            request_uri: request_uri
            method: request_method
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          username:

  # Custom application logs
  - job_name: api_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: api_service
          __path__: /logs/api/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            request_id: request_id
            user_id: user_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          request_id: