# Grafana Datasource Provisioning
# Automatically configure Prometheus and Loki datasources

apiVersion: 1

datasources:
  # Prometheus - Primary metrics datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      timeInterval: "30s"
      queryTimeout: "60s"
      defaultRegion: "default"
      customQueryParameters: ""
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
      cacheLevel: "High"
      incrementalQuerying: true
      incrementalQueryOverlapWindow: "10m"
      disableRecordingRules: false
    exemplarTraceIdDestinations:
      - name: trace_id
        datasourceUid: jaeger

  # Loki - Log aggregation datasource
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"

  # Alertmanager - Alert management
  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://alertmanager:9093
    version: 1
    editable: true
    jsonData:
      implementation: "prometheus"
      handleGrafanaManagedAlerts: true

  # Vector Metrics - Log processing metrics
  - name: Vector-Logs
    type: prometheus
    access: proxy
    url: http://vector:9598
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"

  # TestData - For demo purposes
  - name: TestData
    type: testdata
    uid: testdata
    version: 1
    editable: false
    isDefault: false