apiVersion: v1
kind: Namespace
metadata:
  name: media-platform
  labels:
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: media-platform-staging
  labels:
    istio-injection: enabled
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: media-platform-monitoring
  labels:
    monitoring: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-platform-quota
  namespace: media-platform
spec:
  hard:
    requests.cpu: "1000"
    requests.memory: "1000Gi"
    requests.storage: "10Ti"
    persistentvolumeclaims: "100"
    services.nodeports: "0"  # Disable NodePort services
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: media-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: media-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-istio
  namespace: media-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector:
        matchLabels:
          app: istio-ingressgateway