---
###############################################################
#                   Authelia Configuration                    #
###############################################################

# Server Configuration
server:
  address: 'tcp://0.0.0.0:9091'
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'

# Theme Configuration
theme: 'auto'

# JWT Configuration
jwt_secret: '${AUTHELIA_JWT_SECRET}'

# Default redirection URL
default_redirection_url: 'https://home.${DOMAIN}'

# TOTP Configuration
totp:
  disable_reuse_security_policy: false
  issuer: '${DOMAIN}'
  algorithm: 'sha1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

# WebAuthn Configuration
webauthn:
  disable: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'
  timeout: 60s

# Duo Push API Configuration (disabled)
duo_api:
  disable: true

# Authentication Backend
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  refresh_interval: '5m'
  file:
    path: '/config/authelia/users.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

# Password Policy
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

# Access Control
access_control:
  default_policy: 'deny'
  networks:
    - name: 'internal'
      networks:
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '192.168.0.0/16'
    - name: 'VPN'
      networks:
        - '10.9.0.0/16'
  rules:
    # Rules applied to 'admins' group
    - domain: '${DOMAIN}'
      subject: 'group:admins'
      policy: 'one_factor'
      resources:
        - '^/api/.*'
    
    # Rules applied to 'dev' group
    - domain: '${DOMAIN}'
      subject: 'group:dev'
      policy: 'two_factor'
    
    # Authelia portal bypass
    - domain: 'auth.${DOMAIN}'
      policy: 'bypass'
    
    # Default rule for all subdomains
    - domain: '*.${DOMAIN}'
      policy: 'one_factor'
      networks:
        - 'internal'
    
    # External access requires two-factor
    - domain: '*.${DOMAIN}'
      policy: 'two_factor'

# Session Configuration
session:
  name: 'authelia_session'
  same_site: 'lax'
  secret: '${AUTHELIA_SESSION_SECRET}'
  expiration: '1h'
  inactivity: '5m'
  remember_me_duration: '1M'
  cookies:
    - domain: '${DOMAIN}'
      authelia_url: 'https://auth.${DOMAIN}'
      default_redirection_url: 'https://home.${DOMAIN}'
      name: 'authelia_session'
      same_site: 'lax'
      expiration: '1h'
      inactivity: '5m'
      remember_me_duration: '1M'
  redis:
    host: 'authelia_redis'
    port: 6379
    password: '${REDIS_PASSWORD}'
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

# Regulation Configuration
regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

# Storage Configuration
storage:
  encryption_key: '${AUTHELIA_STORAGE_ENCRYPTION_KEY}'
  local:
    path: '/config/db.sqlite3'

# Notifier Configuration
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'

# Identity Providers
identity_providers:
  oidc:
    hmac_secret: '${AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET}'
    issuer_private_key: |
      ${AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY}
    access_token_lifespan: '1h'
    authorize_code_lifespan: '1m'
    id_token_lifespan: '1h'
    refresh_token_lifespan: '90m'
    enable_client_debug_messages: false
    enforce_pkce: 'public_clients_only'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://${DOMAIN}'
        - 'https://*.${DOMAIN}'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: 'jellyfin'
        description: 'Jellyfin Media Server'
        secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://jellyfin.${DOMAIN}/sso/OID/redirect/authelia'
          - 'https://jellyfin.${DOMAIN}/sso/OID/start/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        response_modes:
          - 'form_post'
          - 'query'
          - 'fragment'
        userinfo_signing_algorithm: 'none'

# Logging Configuration
log:
  level: 'info'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: true